### PR TITLE
Makefile: added header file in dependencies

### PR DESCRIPTION
**Pull request by Dhruv-Vanjari**
Added header file as a dependency for the building the binary

### CODE REVIEW

**Review by anarcat — APPROVED** [review]

**Comment by anarcat** [comment]
sigh.. why is TODO Ignored here? I was about to merge this...

**Comment by Dhruv-Vanjari** [comment]
So that everyone can have their own todo list

**Comment by anarcat** [comment]
> So that everyone can have their own todo list

i can appreciate the idea, but it's not related to your original PR, and we *might* want to have a shared one... :)

**Comment by Dhruv-Vanjari** [comment]
Okay, I will do that :)

**Pull request closed without merging**
