### PR TITLE
Synchronization for seconds

### PR DESCRIPTION
**Pull request by sbohmann**
Hi, I added synchronization for accurate display of second changes. It is active when delay is 1 second and nsdelay is zero 🙂 I tried to follow your code style as well as possible but because I used a different IDE than vim, some cleanup might be required.

### CODE REVIEW

**Comment by anarcat** [comment]
i'm having trouble parsing those commits, would you mind rebasing this in something that makes sense? :) it seems you have at least two commits with the same commitlog, which doesn't fit on one line...

i'm sorry to be picky, but this is particularly core and confusing code, and i'd like the record to be clearer here.

in general, an overall description of the previous and new algos in the commitlog would be a great start. having a video or screenshot of before/after would also be appreciated.

for reference, i did a simple screenshot against `xclock -d -update 1`, [vtclock](https://github.com/dse/vtclock/), and my system status bar in https://github.com/xorg62/tty-clock/issues/40, i would also add a `while true; date` kind of loop now.

thanks!

**Comment by sbohmann** [comment]
Certainly 🙂 Just a minute...

**Comment by sbohmann** [comment]
I squashed the commits with a single, hopefully sensible message

**Comment by anarcat** [comment]
FWIW, i consider the xclock code to be the canonical, "correct" implementation of this. running under xwayland will introduce extra latency though and therefore might introduce errors, so be careful with that as well.

**Comment by sbohmann** [comment]
Extra latency should be covered by determining the delay after displaying every time. This also guarantees that there will not be any skew, slowly dragging the timing out of sync.

**Comment by sbohmann** [comment]
PR 103 is ready 🙂 please delete 101 and 102, thanks a lot!

**Comment by anarcat** [comment]
we can't delete PRs, but we (and you) can close them, i'm going to close this one and let you close #102 as an exercise, if you don't mind. :)

**Comment by sbohmann** [comment]
Will do 🙂 I'm so used to bitbucket, it's always good to learn a new tool 🙂

**Pull request closed without merging**
