### PR TITLE
Allow external locale (github #66)

### PR DESCRIPTION
**Pull request by MoonCactus**

### CODE REVIEW

**Comment by MoonCactus** [comment]
OK I have some time to work on this...

Eg. I cherry picked fix #66 as a simple test from the begining of my fork. I did so in a local branch named `locale` on my PC, which I then pushed to my fork on github. And indeed, github magically created a pull request (from me to me? from me to you? this was pretty unclear to me). I though I had "accepted" it from the github web client, but it looks like I "closed" it as if I *refused* the PR (this again was not clear to me, sorry, here I re-open it then)

Can I safely move on with more features or should I wait for you to merge it in your repo in case the subsequent changes depends on this commit (they are not in this precise case, willingly) ?

Actually I do not quite understand the benefit of the github web client when I can merge local or distant branches into my own fork locally with a `git merge --no-ff` without having to go through github specifics
I am not comfortable as well that it asked me to make PR from one of my branch into your master. Usually I would better first merge the feature branch into my own master before even thinking about submitting a PR :thinking: 

Sorry, I am not really accustomed to github.

**Review by anarcat — APPROVED** [review]
lgtm

**Comment by anarcat** [comment]
> OK I have some time to work on this...
> 
> Eg. I cherry picked fix #66 as a simple test from the begining of my fork ina branch named `for_pr` (my master will stay as my master for now b/c that's what I use).

looks good! if i may make a suggestion: if you say "Closes: #66" in the actual commit log (on the third line, for example), it will also automatically close the github issue when this is merged.

> So I created a local branch named `locale` on my PC which I then pushed to my fork on github. And indeed, github magically created a pull request (it was unclear to me and I thought it was initially a PR from me to me, which I also though I had "accepted" it from the github web client. Actually it was probably from my branch to you and I accidentlly "closed" it as if I _refused_ the PR (so here I re-open it then, what a mess)

heh. don't worry, you'll get used to it. you're doing great. :)

> Now... can I safely move on with more features or should I wait for you to merge it in your repo in case the subsequent changes depends on this commit (I made sure they do not for this PR, but next ones might be) ?

i guess that depends on how comfortable you are with juggling many branches around and confident you are that we / I will merge them... ;)

> Actually I do not quite understand the benefit of the github web client when I can merge local or distant branches into my own fork locally with a `git merge --no-ff` without having to go through github specifics

the main advantage i think people find is that they can do review through their web browsers. :p I personnally like the git-based workflow, but it's true that having a central location to pull branches from does serve me well as well.

>     * Moreover I really don't like that it asked me to submit a PR from one of my own branch directly into your master. As before, I would better first merge the feature branch into my own master before I even think about submitting a PR thinking

yeah, typically what i do is i make a branch locally, them merge it in *my* master, then push everything to GH. then GH will ask me to merge my feature branch.

>     * Also, my own policy is to delete the branch once it gets merged into my own master (I want to be sure that I do not recycle old branch names. I also hate long parallel unnecessary branches). Here I am not sure I can safely delete these merged branches (once again, I systematically use `--no-ff`) :/

you can probably delete the branch locally if you pushed it to GH. worst case will be you would have to recreate the branch (based on the remote GH branch) if you need to work on it again.

obviously, you can delete the branch once it's merged into upstream as well, of course. GH will also suggest doing that once the PR is merged.

> Sorry, I am not really accustomed to github.

this will make much more sense once you go a complete iteration as well. :)

keep in mind that the workflow here is that i'm not the primary maintainer of this repo (xorg62 is). i typically mark PRs as "approved" and then wait a few days to give them a chance to review, and then merge them if there's no objection.

**Comment by MoonCactus** [comment]
Thanks for your time :+1: Your answers and policy makes sense and learning is what keeps me going here -- otherwise I'd feel I would somehow be doing the job twice, esp. if I need to rewrite part of what I did which suits me already ("time format string" vs. a few more flags, ouch)

Nb: weirdly, when I push my master branch into my own fork, github suggested no PR, though it did when I pushed my local branch to it :thinking: I usually do sync my local branches to the remote as a backup _before_ I merge them into my master, and this might have triggered the PR and prevented the subsequent better suited PR from my master (imo).
Then I usually delete merged branches both locally *and* remotely (so that a `fetch --all` gets only active branches even from other developpers). Now, I think I'll be cautious and wait for the merge before the next step ;)

These policies are sound though

**Comment by anarcat** [comment]
> Thanks for your time +1 Your answers and policy makes sense and learning is what keeps me going here -- otherwise I'd feel I would somehow be doing the job twice, esp. if I need to rewrite part of what I did which suits me already ("time format string" vs. a few more flags, ouch)

yeah for sure, it's the tradgedy of the commons i guess :p



> Nb: weirdly, when I push my master branch into my own fork, github suggested no PR, though it did when I pushed my local branch to it thinking

i think it might be because the branch is named "master". you could still propose a PR, but it doesn't suggest it unless it's especially named. 



>  usually do sync my local branches to the remote as a backup _before_ I merge them into my master, and this might have triggered the PR and prevented the subsequent better suited PR from my master (imo).

that too.



>  Then I usually delete merged branches both locally _and_ remotely (so that a `fetch --all` gets only active branches even from other developpers). Now, I think I'll be cautious and wait for the merge before the next step ;)

yeah that makes sense too.

**Pull request merged**
